import Head from "next/head";

export default function Layout({children}){
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="navbar p-2">
                <h1>
                    Github Jobs
                </h1>
            </div>
            <main className="main-wrapper">{children}</main>
        </>
    )
}
